apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-postgres
  namespace: kafka
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: 192.168.49.2
    database.port: 32123
    database.user: postgres
    database.password: root
#    database.user: ${secrets:kafka/debezium-secret:username}
#    database.password: ${secrets:kafka/debezium-secret:password}
    database.dbname: orders
    database.server.name: orders_server
    tabe.include.list: public.outbox
    topic.prefix: orders_server
    topic.creation.enable: true
    topic.creation.default.replication.factor: 1
    topic.creation.default.partitions: 1
    topic.creation.default.cleanup.policy: compact
    topic.creation.default.compression.type: lz4
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState