# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
spec:
  selector:
    app: postgresql-db
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

#  minikube service --url postgresql-db-service