# PostgreSQL StatefulSet with ConfigMap and Secret
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 2
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: debezium/postgres:latest
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          envFrom:
# Config from postgres-configmap
            - configMapRef:
                name: postgres-db-config
# Secret from postgres-secret
            - secretRef:
                name: postgres-db-secret
# Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi