#Consumer service
kind: Service
apiVersion: v1
metadata:
  name: consumer-service
  labels:
    name: consumer-service
spec:
  ports:
    - nodePort: 30164
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: consumer
  type: NodePort

#  minikube service --url consumer-service
#  minikube service consumer-service
#  kubectl logs -f pod-name