#Produscer service
kind: Service
apiVersion: v1
metadata:
  name: producer-service
  labels:
    name: producer-service
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: producer
  type: NodePort

#  minikube service --url producer-service
#  minikube service producer-service
#  kubectl logs -f pod-name